# -*- coding: utf-8 -*-
"""Build the three offline design specimens. No application files are touched."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parent
CSS = r'''
:root{color-scheme:light;--canvas:#EEEAE2;--paper:#FFFCF6;--soft:#E8E2D8;--ink:#29252D;--muted:#625C65;--line:#CFC6BD;--edge:#827784;--accent:#684563;--on-accent:#FFFFFF;--tint:#EDE1EA;--good:#286047;--good-bg:#E0EBDF;--warn:#805017;--warn-bg:#F4E7CF;--danger:#B02D32;--danger-bg:#FAE5E0;--on-danger:#FFFFFF}
html[data-theme=dark]{color-scheme:dark;--canvas:#201E23;--paper:#29262D;--soft:#36313A;--ink:#F4EEE6;--muted:#C3B8C5;--line:#514853;--edge:#A698AA;--accent:#D9B6D0;--on-accent:#29252D;--tint:#463443;--good:#ACD7B8;--good-bg:#2D4033;--warn:#F0C182;--warn-bg:#493922;--danger:#FFA7A0;--danger-bg:#502D30;--on-danger:#29252D}
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden}body{font:15px/1.5 "Segoe UI","Microsoft JhengHei",sans-serif;color:var(--ink);background:var(--canvas)}button,input,select{font:inherit}button,a,input,select{outline-offset:4px}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible{outline:3px solid var(--accent)}button,a{touch-action:manipulation}button{cursor:pointer}a{color:inherit;text-decoration:none}button{color:var(--ink);background:var(--paper);border:1px solid var(--edge);border-radius:10px;min-height:40px;padding:8px 16px;font-weight:600}button:hover{background:var(--soft)}button.primary{background:var(--accent);color:var(--on-accent);border-color:var(--accent)}button.small{padding:5px 12px;min-height:34px;font-size:13px}button:disabled{cursor:default;opacity:.65}.quiet{background:transparent;border-color:transparent}p,h1,h2,h3{margin:0}h1{font:600 32px/1.25 Georgia,"PMingLiU",serif;letter-spacing:.02em}h2{font-size:20px;line-height:1.4}h3{font-size:16px}.muted{color:var(--muted)}.eyebrow{font-size:12px;letter-spacing:.14em;text-transform:uppercase;color:var(--muted);font-weight:700}.num{font-variant-numeric:tabular-nums}.row{display:flex;align-items:center;gap:12px}.between{justify-content:space-between}.stack{display:grid;gap:12px}.pill{display:inline-flex;align-items:center;gap:7px;border-radius:99px;padding:5px 12px;background:var(--soft);font-size:13px;font-weight:600}.good{color:var(--good);background:var(--good-bg)}.warning{color:var(--warn);background:var(--warn-bg)}.danger-text{color:var(--danger)}.divider{border-top:1px solid var(--line)}
.app{height:100dvh;display:grid;grid-template-rows:72px minmax(0,1fr) 28px;overflow:hidden}.top{display:flex;align-items:center;gap:36px;padding:0 32px;border-bottom:1px solid var(--line);background:var(--paper)}.brand{display:flex;gap:10px;align-items:center;font:700 23px Georgia,serif;letter-spacing:.04em}.brand-mark{display:grid;place-items:center;border:2px solid var(--accent);color:var(--accent);border-radius:50%;height:32px;width:32px;font:24px Georgia,serif}.navigation{display:flex;align-self:stretch;gap:8px}.navigation a,.navigation button{display:grid;place-content:center;padding:0 18px;border:0;background:none;border-radius:0;color:var(--muted);font-size:15px;font-weight:600;position:relative}.navigation .active{color:var(--accent)}.navigation .active:after{content:"";position:absolute;bottom:0;height:4px;background:var(--accent);left:18px;right:18px;border-radius:4px 4px 0 0}.top-right{margin-left:auto;display:flex;align-items:center;gap:16px}.connection{font-size:13px}.page{min-height:0;min-width:0;padding:24px 32px 20px;display:grid;grid-template-rows:60px minmax(0,1fr);gap:16px}.page-heading{display:flex;align-items:center;justify-content:space-between;gap:16px}.page-heading p{font-size:13px;color:var(--muted);margin-top:4px}.footer{font-size:12px;color:var(--muted);padding:0 32px;display:flex;align-items:center;justify-content:space-between}.sheet{background:var(--paper);border:1px solid var(--line);border-radius:20px;overflow:hidden;min-height:0;min-width:0}.section-title{display:flex;align-items:center;justify-content:space-between;gap:12px}.local-scroll{min-height:0;overflow:auto;overscroll-behavior:contain;scrollbar-color:var(--edge) var(--soft);scrollbar-width:thin}.segment{display:flex;gap:4px;padding:3px;border-radius:12px;background:var(--soft)}.segment button{border:0;background:none;min-height:30px;padding:4px 12px;font-size:13px;border-radius:9px}.segment button[aria-pressed=true]{background:var(--paper);color:var(--accent)}
.live-sheet{display:grid;grid-template-rows:68px minmax(0,1fr) 92px}.coach{padding:12px 28px;display:flex;gap:16px;align-items:center;background:var(--good-bg);color:var(--good);border-bottom:1px solid var(--line)}.coach-symbol{font-size:30px;font-weight:700}.coach h2{font-size:27px}.coach small{font-size:13px}.coach .hold-copy{margin-left:auto;text-align:right}.live-main{display:grid;grid-template-columns:1.06fr 1fr;min-height:0}.metric{padding:24px 32px;display:flex;flex-direction:column;min-height:0;justify-content:center}.metric-number{font:500 clamp(88px,9vw,144px)/1 "Segoe UI",sans-serif;letter-spacing:-.065em;margin:0 0 10px}.metric-number .unit{font-size:.43em;vertical-align:top;line-height:1.65;margin-left:8px;letter-spacing:0}.metric-label{font-size:15px;font-weight:600;color:var(--muted)}.metric-caption{display:flex;gap:16px;font-size:14px}.target-meter{margin-top:22px}.meter{height:18px;background:var(--soft);position:relative;border-radius:20px;margin:8px 0 10px}.meter .target{position:absolute;left:50%;width:12.5%;height:100%;background:var(--good-bg);border:2px solid var(--good)}.meter .point{position:absolute;left:53.75%;top:-7px;height:32px;width:4px;background:var(--ink)}.meter .limit{position:absolute;left:84.375%;height:26px;top:-4px;border-left:2px dashed var(--danger)}.meter-labels{display:flex;justify-content:space-between;font-size:12px;color:var(--muted)}.pose{position:relative;background:var(--soft);margin:16px 16px 16px 0;border-radius:14px;padding:16px 20px;display:grid;grid-template-rows:34px minmax(0,1fr) auto;min-height:0}.pose-svg{height:100%;width:100%;min-height:0;color:var(--accent)}.pose-svg text{font-family:"Segoe UI","Microsoft JhengHei",sans-serif;fill:var(--muted);font-size:13px}.pose-note{font-size:12px;color:var(--muted)}.session-dock{border-top:1px solid var(--line);display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:24px;align-items:center;padding:12px 28px}.dock-value{font-size:28px;line-height:1.2;font-weight:600}.dock-label{font-size:12px;color:var(--muted);margin-bottom:4px}.hold-track{height:5px;background:var(--soft);border-radius:5px;margin-top:6px;max-width:150px}.hold-track span{display:block;width:60%;height:100%;background:var(--good)}.status-select{max-width:190px;border:1px solid var(--edge);background:var(--paper);color:var(--ink);border-radius:8px;padding:7px;font-size:13px}.live-sheet[data-state=alarm] .coach,.live-sheet[data-state=error] .coach{background:var(--danger-bg);color:var(--danger)}.live-sheet[data-state=alarm],.live-sheet[data-state=error]{border:4px solid var(--danger)}.live-sheet[data-state=alarm] .metric-number{color:var(--danger)}.live-sheet[data-state=error] .metric-number{font-size:74px;letter-spacing:0}.live-sheet[data-state=error] .pose-svg{opacity:.25}.live-sheet[data-state=error] .target-meter{visibility:hidden}.live-sheet[data-state=uncalibrated] .coach,.live-sheet[data-state=disconnected] .coach{background:var(--warn-bg);color:var(--warn)}
.settings-sheet{display:grid;grid-template-columns:216px minmax(0,1fr)}.settings-nav{padding:22px 16px;border-right:1px solid var(--line);display:flex;flex-direction:column;gap:8px}.settings-nav button{text-align:left;border:0;background:none;font-weight:500;display:flex;justify-content:space-between}.settings-nav button.active{background:var(--tint);color:var(--accent);font-weight:700}.settings-nav .nav-note{margin-top:auto;padding:12px;font-size:12px;color:var(--muted)}.settings-content{min-width:0;min-height:0;display:grid;grid-template-rows:minmax(0,1fr) 54px}.settings-pane{padding:24px 32px}.settings-pane[hidden]{display:none}.settings-pane h2{font:600 26px/1.3 Georgia,"PMingLiU",serif;margin-bottom:8px}.settings-pane .intro{max-width:780px;color:var(--muted);font-size:14px;margin-bottom:20px}.setting-row{display:flex;justify-content:space-between;align-items:center;gap:20px;padding:18px 0;border-top:1px solid var(--line)}.setting-row p{font-size:13px;color:var(--muted);margin-top:4px}.switch{position:relative;display:flex;align-items:center;gap:10px;font-weight:600;white-space:nowrap}.switch input{appearance:none;margin:0;width:46px;height:26px;border-radius:26px;background:var(--soft);border:1px solid var(--edge);cursor:pointer}.switch input:before{content:"";display:block;width:18px;height:18px;margin:3px;background:var(--muted);border-radius:50%}.switch input:checked{background:var(--accent);border-color:var(--accent)}.switch input:checked:before{transform:translateX(20px);background:var(--on-accent)}.disclosure{display:grid;grid-template-columns:1fr 1fr;gap:28px;border-top:1px solid var(--line);padding:18px 0}.disclosure h3{margin-bottom:8px}.disclosure p{font-size:13px;color:var(--muted);line-height:1.7}.notice{padding:12px 16px;border-radius:10px;font-size:13px;color:var(--warn);background:var(--warn-bg)}details{margin-top:16px}summary{cursor:pointer;color:var(--accent);font-weight:600;font-size:14px}.field{display:grid;gap:6px;margin-top:12px}.field input,.field select{width:100%;border:1px solid var(--edge);background:var(--paper);color:var(--ink);border-radius:8px;min-height:40px;padding:8px 12px}.settings-bottom{padding:12px 32px;border-top:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;font-size:12px;color:var(--muted)}.step-list{list-style:none;padding:0;margin:16px 0;display:grid;gap:10px}.step-list li{padding:12px;border-bottom:1px solid var(--line)}
.review-sheet{display:grid;grid-template-rows:88px minmax(0,1fr)}.review-metrics{display:grid;grid-template-columns:repeat(6,1fr);border-bottom:1px solid var(--line);padding:16px 24px;gap:20px}.review-metrics>div+div{border-left:1px solid var(--line);padding-left:20px}.review-metrics small{font-size:12px;color:var(--muted);display:block}.review-metrics strong{font-size:26px;font-weight:600}.review-metrics strong span{font-size:13px}.review-body{display:grid;grid-template-columns:minmax(0,1fr) 310px;min-height:0}.review-chart-area{padding:20px 24px;min-height:0;display:grid;grid-template-rows:30px minmax(110px,1fr) 64px 26px;gap:8px}.chart{width:100%;height:100%;min-height:0;overflow:visible}.chart text{font:12px "Segoe UI",sans-serif;fill:var(--muted)}.chart .gridline{stroke:var(--line);stroke-width:1}.chart .trace{stroke:var(--accent);stroke-width:3;fill:none;stroke-linejoin:round}.chart .threshold{stroke:var(--danger);stroke-width:1.5;stroke-dasharray:5 5}.rep-strip{display:grid;grid-template-columns:repeat(9,1fr);gap:6px}.rep-strip button{padding:4px;min-height:54px;border-color:var(--edge);font-size:12px;background:var(--soft)}.rep-strip button[aria-pressed=true]{border:2px solid var(--accent);background:var(--tint)}.rep-strip .rep-warn{border-bottom:3px solid var(--danger)}.rep-strip span{display:block;font-weight:400}.review-aside{border-left:1px solid var(--line);padding:20px;display:grid;grid-template-rows:auto auto minmax(0,1fr);gap:16px}.rep-detail{border-bottom:1px solid var(--line);padding-bottom:16px}.rep-detail-values{display:flex;justify-content:space-between;margin-top:10px}.rep-detail-values strong{font-size:25px}.rep-detail-values small{display:block;font-size:12px;color:var(--muted)}.comparison table{width:100%;border-collapse:collapse;font-size:13px;margin-top:12px}.comparison th,.comparison td{padding:7px 0;text-align:right;border-bottom:1px solid var(--line)}.comparison th:first-child,.comparison td:first-child{text-align:left}.comparison p{font-size:12px;color:var(--muted);margin-top:10px}.chart-caption{font-size:12px;color:var(--muted)}.legend{font-size:12px;display:flex;gap:12px;align-items:center}.legend-line{display:inline-block;width:20px;border-top:3px solid var(--accent);margin-right:5px}.legend-band{display:inline-block;width:18px;height:10px;background:var(--good-bg);border:1px solid var(--good);margin-right:5px}
dialog{color:var(--ink);background:var(--paper);border:1px solid var(--edge);border-radius:20px;padding:24px;max-width:min(580px,90vw);max-height:85dvh;overflow:auto}dialog::backdrop{background:#17111c99}dialog h2{margin-bottom:12px}dialog p{margin:10px 0}dialog .row{justify-content:flex-end;margin-top:20px}#toast{position:fixed;bottom:42px;left:50%;transform:translateX(-50%);background:var(--ink);color:var(--paper);padding:10px 20px;border-radius:12px;max-width:85vw;font-size:14px;z-index:10}#toast:empty{display:none}[hidden]{display:none!important}
@media(min-width:1600px) and (min-height:850px){.page{padding:32px 48px 28px;grid-template-rows:80px minmax(0,1fr);gap:24px}h1{font-size:40px}.live-sheet{grid-template-rows:92px minmax(0,1fr) 112px}.coach{padding:16px 40px}.coach h2{font-size:36px}.metric{padding:40px 56px}.metric-number{font-size:176px}.metric-label{font-size:20px}.pose{margin:24px 24px 24px 0;padding:24px 32px}.session-dock{padding:20px 40px}.dock-value{font-size:36px}.review-sheet{grid-template-rows:110px minmax(0,1fr)}.review-body{grid-template-columns:minmax(0,1fr) 390px}.review-metrics strong{font-size:36px}.review-chart-area{padding:28px 32px;grid-template-rows:40px minmax(0,1fr) 78px 30px}.settings-sheet{grid-template-columns:260px minmax(0,1fr)}.settings-pane{padding:40px 48px}.settings-pane .intro{font-size:16px}.setting-row{padding:28px 0}.disclosure{padding:28px 0}.disclosure p{font-size:15px}}
@media(max-height:650px),(max-width:1100px){.app{grid-template-rows:60px minmax(0,1fr) 24px}.top{padding:0 20px;gap:20px}.navigation{gap:0}.navigation a,.navigation button{padding:0 12px}.top-right{gap:8px}.page{padding:14px 20px 12px;grid-template-rows:52px minmax(0,1fr);gap:10px}h1{font-size:27px}.live-sheet{grid-template-rows:58px minmax(0,1fr) 78px}.coach{padding:8px 20px}.coach h2{font-size:23px}.metric{padding:14px 24px}.metric-number{font-size:88px;margin-bottom:4px}.target-meter{margin-top:12px}.pose{margin:12px 12px 12px 0;padding:10px 14px}.session-dock{padding:10px 20px;gap:16px}.dock-value{font-size:25px}.settings-sheet{grid-template-columns:180px minmax(0,1fr)}.settings-nav{padding:14px 10px;gap:4px}.settings-pane{padding:20px 24px}.settings-pane .intro{margin-bottom:12px}.setting-row,.disclosure{padding:12px 0}.review-sheet{grid-template-rows:76px minmax(0,1fr)}.review-metrics{padding:12px 18px;gap:10px}.review-metrics>div+div{padding-left:12px}.review-metrics strong{font-size:23px}.review-body{grid-template-columns:minmax(0,1fr) 280px}.review-chart-area{padding:14px 18px;grid-template-rows:28px minmax(80px,1fr) 54px 22px;gap:6px}.review-aside{padding:14px;gap:10px}.review-aside .notice{padding:8px 10px}.rep-detail{padding-bottom:10px}.footer{padding:0 20px}}
@media(max-width:800px){.connection,.brand-word,.page-heading .eyebrow,.coach small,.hold-copy,.metric-caption{display:none}.top{gap:8px;padding:0 12px}.navigation a,.navigation button{font-size:13px;padding:0 8px}.top-right button{padding:6px 9px}.page{padding:10px 12px;grid-template-rows:48px minmax(0,1fr)}h1{font-size:23px}.page-heading p{font-size:12px}.page-heading .pill{display:none}.page-heading .row{gap:4px}.status-select{max-width:145px;font-size:12px}.live-main{grid-template-columns:1fr 1fr}.metric{padding:12px}.metric-number{font-size:72px}.metric-label{font-size:13px}.pose{padding:8px;margin:8px 8px 8px 0}.pose .section-title h3{display:none}.pose-note{font-size:12px}.session-dock{grid-template-columns:1fr 1fr auto;padding:8px 12px;gap:12px}.dock-time{display:none}.coach h2{font-size:21px}.settings-sheet{grid-template-columns:145px minmax(0,1fr)}.settings-nav{overflow:auto}.settings-nav button{font-size:13px;padding:8px}.settings-pane{padding:16px}.disclosure{grid-template-columns:1fr;gap:12px}.review-body{grid-template-columns:minmax(0,1fr)}.review-aside{display:none}.review-metrics{grid-template-columns:repeat(3,1fr)}.review-metrics>div:nth-child(n+4){display:none}.review-chart-area .legend{display:none}.footer span:last-child{display:none}.settings-bottom{padding:10px 16px}.review-chart-area{grid-template-rows:28px minmax(40px,1fr) 54px 22px}}
@media(max-height:450px){.app{grid-template-rows:48px minmax(0,1fr) 20px}.page{grid-template-rows:40px minmax(0,1fr);gap:6px;padding-top:6px;padding-bottom:6px}.live-sheet{grid-template-rows:46px minmax(0,1fr) 62px}.pose-note,.target-meter{display:none}.metric-number{font-size:56px}.coach{padding:4px 12px}.coach h2{font-size:20px}.coach-symbol{font-size:22px}.dock-value{font-size:22px}.review-sheet{grid-template-rows:64px minmax(0,1fr)}.review-chart-area{grid-template-rows:22px minmax(0,1fr) 44px;gap:4px;padding:8px 12px}.chart-caption{display:none}.rep-strip button{min-height:40px}.page-heading p{display:none}}
.live-sheet[data-state=alarm],.live-sheet[data-state=error]{grid-template-rows:112px minmax(0,1fr) 92px}.live-sheet[data-state=alarm] .coach h2,.live-sheet[data-state=error] .coach h2{font-size:40px;line-height:1.2}.live-sheet:not([data-state=holding]) .hold-copy{display:none}.live-sheet[data-state=alarm] .pose-svg{visibility:hidden}.live-sheet[data-state=alarm] .target-meter,.live-sheet[data-state=error] .target-meter{display:none}.session-dock button{min-height:48px}.session-dock button:first-child:not(.primary){border-color:var(--danger);color:var(--danger)}.live-sheet[data-state=alarm] .coach-symbol,.live-sheet[data-state=error] .coach-symbol{font-size:48px}
@media(max-height:450px){.live-sheet[data-state=alarm],.live-sheet[data-state=error]{grid-template-rows:76px minmax(0,1fr) 62px}.live-sheet[data-state=alarm] .coach h2,.live-sheet[data-state=error] .coach h2{font-size:28px}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
'''

COMMON_JS = r'''
// 所有互動只改變這份設計稿，不存檔、不呼叫裝置或網路。
const $ = s => document.querySelector(s);
$('#theme').onclick = () => { const dark = document.documentElement.dataset.theme !== 'dark'; document.documentElement.dataset.theme = dark ? 'dark' : 'light'; $('#theme').textContent = dark ? '☀ 日間' : '☾ 夜間'; $('#theme').setAttribute('aria-pressed', String(dark)); };
let toastTimer;
function toast(text){$('#toast').textContent=text; clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('#toast').textContent='',3500)}
document.querySelectorAll('[data-message]').forEach(b=>b.onclick=()=>toast(b.dataset.message));
document.querySelectorAll('[data-dialog]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.dialog).showModal());
document.querySelectorAll('dialog [data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
'''

def shell(page, title, subtitle, content, heading='', script='', dialogs=''):
    nav = [('dashboard','即時監測'),('actions','動作處方'),('history-review','療程紀錄'),('settings','設定')]
    links = ''.join(f'<a href="mockup-{key}.html" class="{"active" if key == page else ""}" {"aria-current=page" if key == page else ""}>{name}</a>' if key != 'actions' else '<button data-dialog="actions-dialog">動作處方</button>' for key,name in nav)
    action_dialog = '''<dialog id="actions-dialog"><h2>動作處方 · 版面預覽</h2><p class="muted">完整配置見 PROPOSAL.md。每個動作分成名稱列與固定參數列，長標籤不擠壓按鈕。</p><div class="setting-row"><div><h3>直膝後擺</h3><p>大腿後伸 ≥20° · 保持 2 秒 · 超限 30°</p></div><span class="pill">肢段後伸</span></div><div class="setting-row"><div><h3>坐姿屈膝</h3><p>膝角 80–100° · 保持 3 秒 · 超限 135°</p></div><span class="pill">關節角度</span></div><div class="setting-row"><div><h3>直膝抬腿</h3><p>大腿仰角 ≥45° · 保持 3 秒 · 超限 80°</p></div><span class="pill">肢段抬高</span></div><div class="row"><button data-close>返回</button></div></dialog>'''
    return f'''<!doctype html><html lang="zh-Hant" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} · IRMS 復健工作簿</title><style>{CSS}</style></head><body><div class="app"><header class="top"><a class="brand" href="mockup-dashboard.html" aria-label="IRMS 即時監測"><span class="brand-mark">∿</span><span class="brand-word">IRMS</span></a><nav class="navigation" aria-label="主導覽">{links}</nav><div class="top-right"><span class="connection">○ 設計預覽 · 離線</span><button id="theme" class="small quiet" aria-pressed="false" aria-label="切換日間與夜間主題">☾ 夜間</button></div></header><main class="page"><header class="page-heading"><div><h1>{title}</h1><p>{subtitle}</p></div>{heading}</header>{content}</main><footer class="footer"><span>IRMS / 復健工作簿 · 設計提案 03</span><span>所有數值皆為示意 · 不連線、不儲存、不上傳</span></footer></div><div id="toast" role="status"></div>{action_dialog}{dialogs}<script>{COMMON_JS}{script}</script></body></html>'''

POSE = '''<svg class="pose-svg" id="pose-drawing" viewBox="0 0 440 290" role="img" aria-label="側面示意：大腿水平，小腿向下，屈膝約 86 度；非量測影像"><defs><linearGradient id="limb"><stop stop-color="var(--accent)"/><stop offset="1" stop-color="var(--muted)"/></linearGradient></defs><g class="pose-ground" fill="none" stroke="var(--line)"><ellipse cx="246" cy="259" rx="132" ry="17"/><path d="M50 259H395 M88 79V250H193" stroke-width="2"/><path d="M172 30V258" stroke-dasharray="4 5"/></g><path d="M100 35 L113 90 L249 97" fill="none" stroke="var(--edge)" stroke-width="24" stroke-linecap="round" opacity=".45"/><path d="M118 92 L249 97" fill="none" stroke="url(#limb)" stroke-width="25" stroke-linecap="round"/><path d="M249 97 L258 234 L294 240" fill="none" stroke="var(--accent)" stroke-width="20" stroke-linecap="round" stroke-linejoin="round"/><circle cx="249" cy="97" r="17" fill="var(--paper)" stroke="var(--accent)" stroke-width="4"/><circle cx="249" cy="97" r="5" fill="var(--accent)"/><path d="M198 96 Q201 143 252 148" fill="none" stroke="var(--good)" stroke-width="2"/><path d="M249 97 L330 97" stroke="var(--edge)" stroke-dasharray="4 5"/><text x="173" y="63">大腿</text><text x="289" y="180">小腿</text><text x="192" y="162" style="fill:var(--good);font-size:18px;font-weight:600">86°</text><text x="315" y="35">前方 →</text><text x="53" y="280">側面 / 矢狀面</text></svg>'''

dashboard = f'''<section class="sheet live-sheet" id="live" data-state="holding" aria-label="即時監測示意"><div class="coach" aria-live="polite"><span class="coach-symbol" id="coach-symbol">✓</span><div><h2 id="coach-title">很好，保持這個位置</h2><small id="coach-sub">已進入目標區間，保持滿 3 秒後再回位。</small></div><div class="hold-copy"><strong id="remaining">再保持 1.2 秒</strong><br><small>第 7 次 · 保持中</small></div></div><div class="live-main"><div class="metric"><p class="metric-label">主指標 · 膝關節夾角</p><div class="metric-number num" id="metric-number">86<span class="unit">°</span></div><div class="metric-caption"><span><strong>80–100°</strong> 目標區間</span><span class="muted">超限門檻 135°</span></div><div class="target-meter" aria-label="目前 86 度，目標 80 至 100 度，超限門檻 135 度"><div class="meter"><span class="target"></span><span class="limit"></span><span class="point" id="meter-point"></span></div><div class="meter-labels"><span>0° / 起始</span><span>目標 80–100°</span><span>135° 超限</span><span>160°</span></div></div></div><div class="pose"><div class="section-title"><h3>動作姿態</h3><div class="segment" aria-label="姿態檢視"><button id="pose-2d" aria-pressed="true">2D 側面</button><button id="pose-3d" aria-pressed="false">3D 概念</button></div></div>{POSE}<p class="pose-note" id="pose-note">✓ 已完成校準 · 14:02　／　側向角度未驗證<br>姿態為方向示意；不判讀內外翻。</p></div></div><div class="session-dock"><div><div class="dock-label">已完成</div><div class="dock-value num">6 <span class="muted" style="font-size:15px">次</span></div></div><div><div class="dock-label">本次保持</div><div class="dock-value num" id="hold-value">1.8 <span class="muted" style="font-size:15px">/ 3.0 秒</span></div><div class="hold-track"><span id="hold-fill"></span></div></div><div class="dock-time"><div class="dock-label">療程時間</div><div class="dock-value num">02:18</div></div><div class="row"><button id="alarm-mute" hidden>靜音 30 秒</button><button class="primary" data-dialog="finish-dialog">結束療程</button></div></div></section>'''
dashboard_js = r'''
const stateCopy={holding:['✓','很好，保持這個位置','已進入目標區間，保持滿 3 秒後再回位。','86'],alarm:['!','超出上限，請停止加深','目前 142° · 超限門檻 135° · 警報仍有效。','142'],error:['×','感測器異常 · ERR:1','請停止動作，檢查感測器連接；等待裝置復原。','—'],disconnected:['○','裝置未連線','請先連線裝置；目前沒有即時量測。','—'],uncalibrated:['!','請先完成校準','讀數方向尚未確認；此預覽不提供達標提示。','—']};
$('#state-preview').onchange=e=>{const state=e.target.value,c=stateCopy[state];$('#live').dataset.state=state;$('#coach-symbol').textContent=c[0];$('#coach-title').textContent=c[1];$('#coach-sub').textContent=c[2];$('#metric-number').innerHTML=c[3]+(c[3]==='—'?'':'<span class="unit">°</span>');$('#remaining').textContent=state==='holding'?'再保持 1.2 秒':'請查看狀態提示';$('#hold-value').innerHTML=state==='holding'?'1.8 <span class="muted" style="font-size:15px">/ 3.0 秒</span>':'—';$('#hold-fill').style.width=state==='holding'?'60%':'0';$('#alarm-mute').hidden=state!=='alarm';$('#alarm-mute').textContent='靜音 30 秒';$('#meter-point').style.left=state==='alarm'?'88.75%':'53.75%';$('#pose-drawing').style.visibility=state!=='holding'?'hidden':'visible';$('#calibration-chip').textContent=state==='uncalibrated'?'! 尚未校準':'✓ 校準完成';$('#calibration-chip').className='pill '+(state==='uncalibrated'?'warning':'good');$('#pose-note').textContent=state==='holding'?'✓ 已完成校準 · 14:02 ／ 側向角度未驗證。姿態為方向示意；不判讀內外翻。':state==='alarm'?'超限姿態未在此靜態稿中繪製。正式版保留有效即時姿態。':'無可用姿態；完成連線與校準後顯示。';};
$('#alarm-mute').onclick=()=>{$('#alarm-mute').textContent='靜音中 · 示意';toast('僅預覽靜音狀態；超限警示持續顯示。')};
['2d','3d'].forEach(mode=>$('#pose-'+mode).onclick=()=>{['2d','3d'].forEach(m=>$('#pose-'+m).setAttribute('aria-pressed',String(m===mode)));$('#pose-drawing').style.transform=mode==='3d'?'perspective(700px) rotateY(-22deg)':'none';$('#pose-note').textContent=mode==='3d'?'3D 構圖示意（此處為 SVG，非 three.js）。正式版固定斜側視角；Yaw 不可量測、Roll 未驗證。':'✓ 已完成校準 · 14:02 ／ 側向角度未驗證。姿態為方向示意；不判讀內外翻。';});
'''
heading = '''<div class="row"><span class="pill good" id="calibration-chip">✓ 校準完成</span><label class="eyebrow" for="state-preview">狀態預覽</label><select class="status-select" id="state-preview" aria-label="切換設計稿狀態"><option value="holding">保持中</option><option value="alarm">超限警報</option><option value="error">硬體異常 ERR:1</option><option value="disconnected">未連線</option><option value="uncalibrated">未校準</option></select></div>'''
dialogs = '''<dialog id="finish-dialog"><h2>結束這次療程？</h2><p>坐姿屈膝 · 已完成 6 次 · 02:18</p><p class="muted">這是離線設計稿。正式版會保存本次紀錄，並提供療程回顧。</p><div class="row"><button data-close>返回監測</button><a href="mockup-history-review.html" class="pill" style="background:var(--accent);color:var(--on-accent);padding:12px 16px">查看回顧示意</a></div></dialog>'''
(ROOT/'mockup-dashboard.html').write_text(shell('dashboard','坐姿屈膝','Knee flexion · 目標 90° ±10° · 保持 3 秒',dashboard,heading,dashboard_js,dialogs),encoding='utf-8')

telemetry = '''<section class="settings-pane local-scroll" id="pane-telemetry" aria-label="遙測設定"><div class="eyebrow">資料與隱私 / TELEMETRY</div><h2>協助改善裝置連線</h2><p class="intro">選擇是否將診斷資料傳送給 IRMS 開發團隊。本機量測與療程紀錄不受影響。</p><div class="setting-row"><div><h3>即時遙測上傳</h3><p id="telemetry-status">已關閉 · 沒有資料正在上傳</p></div><label class="switch"><span id="telemetry-label">關閉</span><input id="telemetry-toggle" type="checkbox" aria-label="即時遙測上傳（僅設計稿）"></label></div><div class="disclosure"><div><h3>會傳送什麼</h3><p>原始角度封包、連線與韌體更新狀態、App 日誌，以及療程開始／結束資訊、動作名稱、目標與校準參數。</p></div><div><h3>如何保留</h3><p>伺服器保留 90 天；每次啟動使用新的隨機 ID。不主動蒐集姓名、帳號或電腦名稱；本機紀錄照常保存。</p></div></div><div class="notice">! 動作名稱也會上傳。請勿使用病人或個人姓名命名動作。</div><details id="advanced"><summary>進階連線設定</summary><label class="field">伺服器網址<input id="endpoint" type="url" value="https://hina-tw.ddns.net/irms-api" aria-describedby="endpoint-note"></label><p id="endpoint-note" class="muted" style="font-size:12px;margin-top:6px">上傳開啟時鎖定網址。關閉會捨棄尚未送出的資料。</p></details></section>'''
panes = {
'device':('裝置與連線','確認感測器狀態', '<p class="intro">連線狀態與資料新鮮度分開呈現，收到資料才顯示「量測中」。</p><div class="setting-row"><div><h3>IRMS_Device</h3><p>未連線 · 離線設計預覽</p></div><button class="primary" data-message="設計稿不會搜尋或連線 BLE 裝置。">連線裝置</button></div><div class="setting-row"><div><h3>膝關節協定</h3><p>大腿 IMU ＋ 小腿 IMU · 預期取樣 25 Hz</p></div><span class="pill">等待資料</span></div>'),
'calibration':('校準','讓姿態與佩戴方式對齊','<p class="intro">換人、重新佩戴或感測器位置改變後，請重新校準。已校準不代表所有方向都已驗證。</p><div class="notice">療程進行中鎖定校準；請先結束療程。</div><ol class="step-list"><li>01　佩戴確認 → 站直捕捉零位</li><li>02　抬大腿 → 後勾小腿，建立兩段鉸鏈軸</li><li>03　選配側擺 → 預覽確認</li></ol><button class="primary" data-message="校準精靈提案：每步一頁，保留既有六步與驗證規則。">預覽校準流程</button>'),
'display':('顯示與語言','依工作方式調整','<p class="intro">主要角度與姿態常駐；診斷數值由治療師另行開啟。</p><label class="field">介面語言<select><option>繁體中文</option><option>English（提案）</option></select></label><div class="setting-row"><div><h3>主題</h3><p>使用右上角日間／夜間切換檢視配色。</p></div><span class="pill">本頁即時預覽</span></div><details><summary>工程診斷與資料寫入</summary><p class="intro">原始 Pitch、Roll、圖表點數與寫入間隔在此集中管理。Roll 僅用於安裝與軸向排錯，不標示解剖學內外翻。</p></details>'),
'updates':('軟體與韌體','更新工作區','<p class="intro">App 更新與裝置韌體分開操作。療程中禁用韌體燒錄。</p><div class="setting-row"><div><h3>IRMS App</h3><p>目前版本 1.2.0-beta.12 · 版本示意</p></div><button data-message="這是設計稿，不會查詢更新伺服器。">檢查更新</button></div><label class="field">更新頻道<select><option>穩定版</option><option>測試版</option></select></label><div class="setting-row"><div><h3>裝置韌體 OTA</h3><p>需連線裝置並結束療程，才能選擇檔案與確認燒錄。</p></div><button disabled>選擇韌體</button></div>'),
'demo':('示範模式','不接硬體也能演練','<p class="intro">模擬資料會在監測畫面、歷史與匯出中持續標記「示範」，不與真實療程合併比較。</p><label class="field">演練情境<select><option>正常療程 · 連續三次達標</option><option>超限警報</option><option>連線中斷</option></select></label><div class="setting-row"><button class="primary" data-message="此處僅展示設定；請至即時監測使用狀態預覽。">啟用示範</button><button data-message="沒有刪除任何資料。正式版會先顯示示範紀錄筆數並要求確認。">清除示範紀錄</button></div>')}
nav_items=[('device','裝置與連線'),('calibration','校準'),('display','顯示與語言'),('updates','軟體與韌體'),('telemetry','資料與隱私'),('demo','示範模式')]
settings_nav=''.join(f'<button data-pane="{key}" class="{"active" if key=="telemetry" else ""}" aria-pressed="{str(key=="telemetry").lower()}">{name}<span aria-hidden="true">›</span></button>' for key,name in nav_items)
other_panes=''.join(f'<section class="settings-pane local-scroll" id="pane-{key}" hidden aria-label="{v[0]}"><div class="eyebrow">{v[0]}</div><h2>{v[1]}</h2>{v[2]}</section>' for key,v in panes.items())
settings=f'''<section class="sheet settings-sheet"><nav class="settings-nav" aria-label="設定分類">{settings_nav}<div class="nav-note">一次處理一件事。<br>設定內容只在右側捲動。</div></nav><div class="settings-content">{telemetry}{other_panes}<div class="settings-bottom"><span id="settings-save">本頁為設計預覽，不變更實際設定</span><a href="mockup-dashboard.html">返回監測 ↗</a></div></div></section>'''
settings_js=r'''
document.querySelectorAll('[data-pane]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-pane]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});document.querySelectorAll('.settings-pane').forEach(p=>p.hidden=p.id!=='pane-'+button.dataset.pane)});
function telemetryState(on){$('#telemetry-toggle').checked=on;$('#telemetry-label').textContent=on?'開啟':'關閉';$('#telemetry-status').textContent=on?'預覽：已上傳 138 筆 · 待傳 32 筆 · 已捨棄 0 筆':'已關閉 · 沒有資料正在上傳';$('#endpoint').disabled=on;$('#settings-save').textContent='僅更新設計稿狀態 · 未儲存或傳送資料'}
$('#telemetry-toggle').onchange=e=>{if(e.target.checked){e.target.checked=false;$('#telemetry-consent').showModal()}else telemetryState(false)};
$('#confirm-telemetry').onclick=()=>{telemetryState(true);$('#telemetry-consent').close()};
'''
consent='''<dialog id="telemetry-consent"><h2>開啟即時遙測上傳？</h2><p>訓練資訊包含您自訂的動作名稱。若名稱包含病人或個人姓名，請先修改，或維持關閉。</p><p class="muted">此按鈕只預覽開啟狀態，不會傳送資料。</p><div class="row"><button data-close>維持關閉</button><button class="primary" id="confirm-telemetry">確認並預覽開啟</button></div></dialog>'''
(ROOT/'mockup-settings.html').write_text(shell('settings','系統設定','裝置準備、資料選擇，都有各自的位置。',settings,'<span class="eyebrow">SETUP / PREFERENCES</span>',settings_js,consent),encoding='utf-8')

# 示意曲線共九次動作嘗試；第八次未保持足夠時間，第九次超限。
peaks=[88,92,90,94,91,93,96,76,142]
holds=[3.2,3.1,3.4,3.0,3.3,3.1,3.2,0,3.0]
points=[]
for i,peak in enumerate(peaks):
    x=48+i*70
    for dx,v in [(0,10),(10,15),(22,peak),(35,peak),(46,25),(57,10)]:
        points.append(f'{x+dx},{218-v*1.2:.1f}')
curve=' '.join(points)
grid=''.join(f'<line class="gridline" x1="48" x2="688" y1="{218-v*1.2}" y2="{218-v*1.2}"/><text x="35" y="{222-v*1.2}" text-anchor="end">{v}</text>' for v in [0,40,80,120,160])
chart=f'''<svg class="chart" viewBox="0 0 735 258" preserveAspectRatio="none" role="img" aria-label="示意療程膝角曲線：9 次嘗試，8 次完成；第 8 次未達標，第 9 次超限至 142 度"><rect x="48" y="98" width="640" height="24" fill="var(--good-bg)"/>{grid}<line class="threshold" x1="48" x2="688" y1="56" y2="56"/><text x="688" y="46" text-anchor="end" style="fill:var(--danger)">135° 超限門檻</text><polyline class="trace" points="{curve}"/><circle cx="630" cy="47.6" r="5" fill="var(--danger)"/><text x="48" y="244">00:00</text><text x="248" y="244">01:30</text><text x="458" y="244">03:00</text><text x="688" y="244" text-anchor="end">04:30</text><text x="12" y="14">°</text></svg>'''
rep_buttons=''.join(f'<button data-rep="{i}" aria-pressed="{str(i==5).lower()}" class="{"rep-warn" if i>=7 else ""}">{i+1:02}<span>{"! 超限" if i==8 else "○ 未達" if i==7 else "✓ 完成"}</span></button>' for i in range(9))
review=f'''<section class="sheet review-sheet"><div class="review-metrics num"><div><small>完成 / 嘗試</small><strong>8 <span>/ 9 次</span></strong></div><div><small>峰值膝角</small><strong>142<span>°</span></strong></div><div><small>平均膝角</small><strong>48.6<span>°</span></strong></div><div><small>目標區時間</small><strong>29<span>%</span></strong></div><div><small>超限事件</small><strong class="danger-text">1 <span>次 · 1.2 秒</span></strong></div><div><small>有效量測</small><strong>4:30</strong></div></div><div class="review-body"><div class="review-chart-area"><div class="section-title"><h3>每一次，都有跡可循</h3><div class="legend"><span><i class="legend-line"></i>膝角</span><span><i class="legend-band"></i>80–100° 目標</span></div></div>{chart}<div class="rep-strip" aria-label="選擇動作嘗試">{rep_buttons}</div><p class="chart-caption">點選一次動作查看峰值與保持時間 · 所有曲線與摘要數值均為設計示例</p></div><aside class="review-aside local-scroll" aria-label="單次動作與比較"><section class="rep-detail"><div class="section-title"><h3 id="rep-title">第 06 次動作</h3><span class="pill good" id="rep-status">✓ 完成</span></div><div class="rep-detail-values num"><div><small>峰值</small><strong id="rep-peak">93°</strong></div><div><small>最長連續保持</small><strong id="rep-hold">3.1 秒</strong></div></div></section><div class="notice"><strong>! 與上次的校準不同</strong><br>零位或鉸鏈軸已變更。以下僅並列，不計算進步幅度。</div><section class="comparison"><h3>同動作 · 上次療程</h3><table><thead><tr><th>坐姿屈膝</th><th>09/23</th><th>本次</th></tr></thead><tbody><tr><td>完成次數</td><td>7</td><td>8</td></tr><tr><td>峰值</td><td>96°</td><td>142°</td></tr><tr><td>保持中位數</td><td>3.0 秒</td><td>3.15 秒</td></tr></tbody></table><p>同處方：90° ±10° / 3 秒<br>校準 A → B · 跨場比較需由治療師確認<br>本次校準亦與目前設定不同</p></section></aside></div></section>'''
review_js='''
const peaks='''+json.dumps(peaks)+''',holds='''+json.dumps(holds)+''';
document.querySelectorAll('[data-rep]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.rep);document.querySelectorAll('[data-rep]').forEach(r=>r.setAttribute('aria-pressed',String(r===b)));$('#rep-title').textContent='第 '+String(i+1).padStart(2,'0')+' 次動作';$('#rep-peak').textContent=peaks[i]+'°';$('#rep-hold').textContent=holds[i].toFixed(1)+' 秒';$('#rep-status').textContent=i===8?'! 完成 / 超限':i===7?'○ 未達標':'✓ 完成';$('#rep-status').className='pill '+(i>=7?'warning':'good');if(innerWidth<=800)toast('第 '+(i+1)+' 次：峰值 '+peaks[i]+'°，保持 '+holds[i].toFixed(1)+' 秒。比較摘要請開啟「比較」。')});
'''
review_heading='''<div class="row"><button class="small" data-dialog="compare-dialog">比較</button><button class="small" data-message="匯出規格見提案：包含原始樣本、處方快照、校準資訊、資料來源與分析版本。此設計稿不產生假療程檔。">匯出紀錄 ↗</button></div>'''
compare_dialog='''<dialog id="compare-dialog"><h2>同動作比較</h2><div class="notice">! 09/23 與 09/25 使用不同校準；不計算進步幅度。本次校準也與目前設定不同。</div><p>坐姿屈膝 · 同處方：90° ±10° / 3 秒</p><p>09/23：完成 7 次、峰值 96°、保持中位數 3.0 秒。</p><p>09/25：完成 8 次、峰值 142°、保持中位數 3.15 秒。</p><p class="muted">較高峰值包含一次超限，不能解讀為進步。正式版另可選擇可比的歷史療程。</p><div class="row"><button data-close>關閉比較</button></div></dialog>'''
(ROOT/'mockup-history-review.html').write_text(shell('history-review','療程回顧','坐姿屈膝 · 2026/09/25 14:30 · 療程 #24 · 示例資料',review,review_heading,review_js,compare_dialog),encoding='utf-8')
print('Wrote three self-contained HTML mockups.')
